services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      # Next.js/Proxy config (read by server only)
      TRAKT_BASE_URL: ${TRAKT_BASE_URL:-https://api.trakt.tv}
      TRAKT_CLIENT_ID: ${TRAKT_CLIENT_ID}
      TRAKT_API_VERSION: ${TRAKT_API_VERSION:-2}
      PORT: ${PORT:-3000}
      # MongoDB config used by lib/db-mongodb.ts
      MONGODB_URI: ${MONGODB_URI:-mongodb://mongodb:27017}
      MONGODB_DB: ${MONGODB_DB:-trakt-proxy}
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-trakt-proxy}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped

volumes:
  mongodb_data: